spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.134.153:3306/conferenceroom?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: jyq369258
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 8.130.134.153
    port: 6379
    password: jyq369258
    database: 0
  mail:
    host: smtp.qq.com
    username: 1984196795@qq.com
    default-encoding: utf-8
          #移动端客户授权码
    password: ioecgnccwmljehch
    port: 465
    properties:
         mail:
           smtp:
             socketFactory:
               class: javax.net.ssl.SSLSocketFactory


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

#    输出到日志文件中 org.apache.ibatis.logging.slf4j.Slf4jImpl
#    如果是控制台 org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
server:
  port: 8888

shiro-redis:
  enabled: true
  redis-manager:
    host: 8.130.134.153:6379
    password: jyq369258

zyfgoup:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
#token 过期时间 秒 7天
    expire: 604800
    header: Authorization



